In [45]:
import warnings
warnings.filterwarnings('ignore')

In [46]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [47]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [48]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [49]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0    10500.0    0.1719       375.35           RENT     66000.0   
1    25000.0    0.2000       929.09       MORTGAGE    105000.0   
2    20000.0    0.2000       529.88       MORTGAGE     56000.0   
3    10000.0    0.1640       353.55           RENT     92000.0   
4    22000.0    0.1474       520.39       MORTGAGE     52000.0   

  verification_status   issue_d loan_status pymnt_plan    dti  ...  \
0     Source Verified  Mar-2019    low_risk          n  27.24  ...   
1            Verified  Mar-2019    low_risk          n  20.23  ...   
2            Verified  Mar-2019    low_risk          n  24.26  ...   
3            Verified  Mar-2019    low_risk          n  31.44  ...   
4        Not Verified  Mar-2019    low_risk          n  18.76  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            85.7             100.0                   0.0        0.0   
1            91.2              50.0                   1.0        0.0   
2            66.7              50.0                   0.0        0.0   
3           100.0              50.0                   1.0        0.0   
4           100.0               0.0                   0.0        0.0   

   tot_hi_cred_lim  total_bal_ex_mort total_bc_limit  \
0          65687.0            38199.0         2000.0   
1         271427.0            60641.0        41200.0   
2          60644.0            45684.0         7500.0   
3          99506.0            68784.0        19700.0   
4         219750.0            25919.0        27600.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     61987.0              N                     N  
1                     49197.0              N                     N  
2                     43144.0              N                     N  
3                     76506.0              N                     N  
4                     20000.0              N                     N  

[5 rows x 86 columns]

# Data Preprocessing

In [50]:
# df.info() gives list of columns with data types. change all 'object'

# 'home_ownership', 'verification_status', 'issue_d', 'pymnt_plan', 'initial_list_status', 'next_pymnt_d', 
# 'application_type', 'hardship_flag', 'debt_settlement_flag'
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68817 entries, 0 to 68816
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   loan_amnt                   68817 non-null  float64
 1   int_rate                    68817 non-null  float64
 2   installment                 68817 non-null  float64
 3   home_ownership              68817 non-null  object 
 4   annual_inc                  68817 non-null  float64
 5   verification_status         68817 non-null  object 
 6   issue_d                     68817 non-null  object 
 7   loan_status                 68817 non-null  object 
 8   pymnt_plan                  68817 non-null  object 
 9   dti                         68817 non-null  float64
 10  delinq_2yrs                 68817 non-null  float64
 11  inq_last_6mths              68817 non-null  float64
 12  open_acc                    68817 non-null  float64
 13  pub_rec                     688

In [51]:
# preprocess the columns that are object/string with LabelEncoder
from sklearn.preprocessing import LabelEncoder

# list of categorical columns
categorical_columns = ['home_ownership', 'verification_status', 'issue_d', 
                                 'pymnt_plan', 'initial_list_status', 'next_pymnt_d', 'application_type', 
                                 'hardship_flag', 'debt_settlement_flag']

# instantiating LabelEncoder
le = LabelEncoder()
df2 = df.copy()

# for loop for LabelEncoder
for col in df2[categorical_columns]:
    df2[col]= le.fit_transform(df2[col])

In [52]:
# show the df
df2

loan_amnt  int_rate  installment  home_ownership  annual_inc  \
0        10500.0    0.1719       375.35               3     66000.0   
1        25000.0    0.2000       929.09               1    105000.0   
2        20000.0    0.2000       529.88               1     56000.0   
3        10000.0    0.1640       353.55               3     92000.0   
4        22000.0    0.1474       520.39               1     52000.0   
...          ...       ...          ...             ...         ...   
68812    10000.0    0.1502       346.76               3     26000.0   
68813    12000.0    0.2727       368.37               3     63000.0   
68814     5000.0    0.1992       185.62               1     52000.0   
68815    40000.0    0.0646      1225.24               1    520000.0   
68816    16000.0    0.1131       350.36               1     72000.0   

       verification_status  issue_d loan_status  pymnt_plan    dti  ...  \
0                        1        2    low_risk           0  27.24  ...   
1                        2        2    low_risk           0  20.23  ...   
2                        2        2    low_risk           0  24.26  ...   
3                        2        2    low_risk           0  31.44  ...   
4                        0        2    low_risk           0  18.76  ...   
...                    ...      ...         ...         ...    ...  ...   
68812                    1        1    low_risk           0   9.60  ...   
68813                    0        1    low_risk           0  29.07  ...   
68814                    1        1    low_risk           0  14.86  ...   
68815                    2        1    low_risk           0   9.96  ...   
68816                    2        1    low_risk           0   7.02  ...   

       pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0                85.7             100.0                   0.0        0.0   
1                91.2              50.0                   1.0        0.0   
2                66.7              50.0                   0.0        0.0   
3               100.0              50.0                   1.0        0.0   
4               100.0               0.0                   0.0        0.0   
...               ...               ...                   ...        ...   
68812            80.0               0.0                   0.0        0.0   
68813            96.2               0.0                   0.0        0.0   
68814           100.0               0.0                   1.0        0.0   
68815            98.2              12.5                   0.0        0.0   
68816            94.3               0.0                   1.0        0.0   

       tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
0              65687.0            38199.0          2000.0   
1             271427.0            60641.0         41200.0   
2              60644.0            45684.0          7500.0   
3              99506.0            68784.0         19700.0   
4             219750.0            25919.0         27600.0   
...                ...                ...             ...   
68812          20625.0             6798.0         11300.0   
68813          87939.0            60350.0         13500.0   
68814          30592.0            18611.0          3600.0   
68815        1033574.0            95958.0        100800.0   
68816         251486.0            74835.0         23000.0   

       total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                         61987.0              0                     0  
1                         49197.0              0                     0  
2                         43144.0              0                     0  
3                         76506.0              0                     0  
4                         20000.0              0                     0  
...                           ...            ...                   ...  
68812                      5425.0              0                     0  
68813                  

# Split the Data into Training and Testing

In [53]:
# Create our features
# drop 'loan_status' column
X = df2.drop(columns='loan_status')

# Create our target
# set to loan_status
y = df2['loan_status']

In [54]:
X.describe()

loan_amnt      int_rate   installment  home_ownership    annual_inc  \
count  68817.000000  68817.000000  68817.000000    68817.000000  6.881700e+04   
mean   16677.594562      0.127718    480.652863        1.812779  8.821371e+04   
std    10277.348590      0.048130    288.062432        0.941313  1.155800e+05   
min     1000.000000      0.060000     30.890000        0.000000  4.000000e+01   
25%     9000.000000      0.088100    265.730000        1.000000  5.000000e+04   
50%    15000.000000      0.118000    404.560000        1.000000  7.300000e+04   
75%    24000.000000      0.155700    648.100000        3.000000  1.040000e+05   
max    40000.000000      0.308400   1676.230000        3.000000  8.797500e+06   

       verification_status       issue_d  pymnt_plan           dti  \
count         68817.000000  68817.000000     68817.0  68817.000000   
mean              0.669994      0.805542         0.0     21.778153   
std               0.719105      0.714932         0.0     20.199244   
min               0.000000      0.000000         0.0      0.000000   
25%               0.000000      0.000000         0.0     13.890000   
50%               1.000000      1.000000         0.0     19.760000   
75%               1.000000      1.000000         0.0     26.660000   
max               2.000000      2.000000         0.0    999.000000   

        delinq_2yrs  ...  pct_tl_nvr_dlq  percent_bc_gt_75  \
count  68817.000000  ...    68817.000000      68817.000000   
mean       0.217766  ...       95.057627         30.626217   
std        0.718367  ...        8.326426         33.631463   
min        0.000000  ...       20.000000          0.000000   
25%        0.000000  ...       93.000000          0.000000   
50%        0.000000  ...      100.000000         20.000000   
75%        0.000000  ...      100.000000         50.000000   
max       18.000000  ...      100.000000        100.000000   

       pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  total_bal_ex_mort  \
count          68817.000000    68817.0     6.881700e+04       6.881700e+04   
mean               0.125972        0.0     2.100332e+05       6.133843e+04   
std                0.336732        0.0     1.928088e+05       5.738798e+04   
min                0.000000        0.0     3.600000e+03       2.350000e+02   
25%                0.000000        0.0     6.697700e+04       2.650300e+04   
50%                0.000000        0.0     1.467100e+05       4.535700e+04   
75%                0.000000        0.0     3.036400e+05       7.657000e+04   
max                4.000000        0.0     3.292782e+06       1.295455e+06   

       total_bc_limit  total_il_high_credit_limit  hardship_flag  \
count    68817.000000                6.881700e+04        68817.0   
mean     29734.128558                5.572240e+04            0.0   
std      26795.394232                5.095845e+04            0.0   
min        100.000000                1.270000e+02            0.0   
25%      11600.000000                2.288000e+04            0.0   
50%      22100.000000                4.200000e+04            0.0   
75%      39300.000000                7.249900e+04            0.0   
max     509400.000000                1.426964e+06            0.0   

       debt_settlement_flag  
count               68817.0  
mean                    0.0  
std                     0.0  
min                     0.0  
25%                     0.0  
50%                     0.0  
75%                     0.0  
max                     0.0  

[8 rows x 85 columns]

In [55]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

# Scale the Training and Testing Data

In [57]:
# Creating a StandardScaler instance.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [58]:
# Resample the training data with the BalancedRandomForestClassifier
# This is different model from example (RandomForestClassifer)
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=0)
brf.fit(X_train, y_train)

# predictions
y_pred = brf.predict(X_test)

In [59]:
# Calculate the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.7454494361651982

In [11]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
# From starter code, left for reference

0.7885466545953005

In [60]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[   53,    34],
       [ 2025, 15093]])

In [12]:
# Display the confusion matrix
# YOUR CODE HERE

array([[   71,    30],
       [ 2153, 14951]])

In [61]:
# imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.61      0.88      0.05      0.73      0.52        87
   low_risk       1.00      0.88      0.61      0.94      0.73      0.55     17118

avg / total       0.99      0.88      0.61      0.93      0.73      0.55     17205



In [13]:
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.70      0.87      0.06      0.78      0.60       101
   low_risk       1.00      0.87      0.70      0.93      0.78      0.62     17104

avg / total       0.99      0.87      0.70      0.93      0.78      0.62     17205



In [62]:
# List the features sorted in descending order by feature importance
importances = brf.feature_importances_
importances

array([0.01422025, 0.02555978, 0.02011608, 0.0050388 , 0.01987548,
       0.00415777, 0.02199698, 0.        , 0.01669063, 0.0029868 ,
       0.00583694, 0.00705858, 0.00135386, 0.01620902, 0.01082902,
       0.00181031, 0.01730805, 0.01717639, 0.05763024, 0.04686928,
       0.06599576, 0.0563372 , 0.0069838 , 0.        , 0.        ,
       0.07598295, 0.00798589, 0.00024826, 0.        , 0.00163662,
       0.        , 0.00349684, 0.01407296, 0.00399249, 0.00654096,
       0.00634868, 0.00865009, 0.01387623, 0.01307469, 0.01537291,
       0.00440883, 0.0057833 , 0.01834156, 0.01378091, 0.01684121,
       0.00777376, 0.00741682, 0.01035465, 0.00816048, 0.01534838,
       0.01323346, 0.01314681, 0.00033519, 0.        , 0.01721449,
       0.01514863, 0.00864344, 0.00987539, 0.00723603, 0.01088454,
       0.01662884, 0.0024216 , 0.00972168, 0.00854399, 0.00804095,
       0.00840343, 0.01018051, 0.01012404, 0.01117537, 0.00987811,
       0.00740846, 0.        , 0.        , 0.00100713, 0.00637

In [63]:
# Sort the features by their importance.
sorted(zip(brf.feature_importances_, X.columns), reverse=True)

[(0.07598295348040078, 'last_pymnt_amnt'),
 (0.06599576386173596, 'total_rec_prncp'),
 (0.05763023510459347, 'total_pymnt'),
 (0.056337203704566644, 'total_rec_int'),
 (0.046869276221897196, 'total_pymnt_inv'),
 (0.025559778001137238, 'int_rate'),
 (0.021996977589425672, 'issue_d'),
 (0.02011608081242873, 'installment'),
 (0.019875475646163696, 'annual_inc'),
 (0.018341555267066028, 'max_bal_bc'),
 (0.017308050943540015, 'out_prncp'),
 (0.01721449435475379, 'mo_sin_old_il_acct'),
 (0.017176390706890848, 'out_prncp_inv'),
 (0.0168412111126307, 'total_rev_hi_lim'),
 (0.01669062963672291, 'dti'),
 (0.01662883728406897, 'mths_since_recent_inq'),
 (0.016209015570447096, 'revol_bal'),
 (0.015372906672409491, 'il_util'),
 (0.015348376568468892, 'avg_cur_bal'),
 (0.015148631176790531, 'mo_sin_old_rev_tl_op'),
 (0.015120131269276983, 'tot_hi_cred_lim'),
 (0.014482010372160846, 'total_bal_ex_mort'),
 (0.014220251595123754, 'loan_amnt'),
 (0.014072956109489396, 'tot_cur_bal'),
 (0.013876230033696

In [14]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
# from starter code, left for reference

loan_amnt: (0.07876809003486353)
int_rate: (0.05883806887524815)
installment: (0.05625613759225244)
annual_inc: (0.05355513093134745)
dti: (0.0500331813446525)
delinq_2yrs: (0.02966959508700077)
inq_last_6mths: (0.021129125328012987)
open_acc: (0.01980242888931366)
pub_rec: (0.01747062730041245)
revol_bal: (0.016858293184471483)
total_acc: (0.01641297102011915)
out_prncp: (0.015220714904737209)
out_prncp_inv: (0.015115240704562424)
total_pymnt: (0.014926655663448373)
total_pymnt_inv: (0.014899352873994727)
total_rec_prncp: (0.014881069023035237)
total_rec_int: (0.014859446582326507)
total_rec_late_fee: (0.014832564501144122)
recoveries: (0.014613819728800227)
collection_recovery_fee: (0.014487685026878092)
last_pymnt_amnt: (0.013921085423763812)
collections_12_mths_ex_med: (0.013534131593418711)
policy_code: (0.013364759441576994)
acc_now_delinq: (0.01332289882475225)
tot_coll_amt: (0.013265926832893358)
tot_cur_bal: (0.01311545089813887)
open_acc_6m: (0.01304530062898567)
open_act_il:

### Easy Ensemble AdaBoost Classifier

In [64]:
# Instantiate EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

# predictions
y_pred = eec.predict(X_test)

In [65]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.9246971326814686

In [16]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
# Starter code left for reference

0.9316600714093861

In [66]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[   79,     8],
       [ 1004, 16114]])

In [17]:
# Display the confusion matrix
# YOUR CODE HERE
# Starter code left for reference

array([[   93,     8],
       [  983, 16121]])

In [67]:
# imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.07      0.91      0.94      0.14      0.92      0.85        87
   low_risk       1.00      0.94      0.91      0.97      0.92      0.86     17118

avg / total       0.99      0.94      0.91      0.97      0.92      0.86     17205



In [18]:
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205

